services:
  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
